export { default as DescribeSituationandEmotionAssigmentActivity } from './DescribeSituationandEmotionAssigmentActivity'
export { default as EmotionalAssigmentActivity } from './EmotionalAssigmentActivity'
export { default as EmotionRecognitionActivity } from './EmotionRecognitionActivity'
export { default as IdentifyEmotionsActivity } from './IdentifyEmotionsActivity'
export { default as WhatDoilLikeActivity } from './WhatDoilLikeActivity'
