export { default as DescribeSituationandEmotionAssigmentActivity } from './DescribeSituationandEmotionAssigmentActivity'
export { default as EmotionalAssigmentActivity } from './EmotionalAssigmentActivity'
export { default as FacialEmotionActivity } from './FacialEmotionActivity'
export { default as IdentifyEmotionsActivity } from './IdentifyEmotionsActivity'
export { default as WhatDoilLikeActivity } from './WhatDoilLikeActivity'
