export { default as RegisterUserSlide } from './RegisterUserSlide'
export { default as EmailRegisterSlide } from './EmailRegisterSlide'
export { default as TermsConditionsSlide } from './TermsConditionsSlide'
export { default as UsernameSlide } from './UsernameSlide'
export { default as DataGeneralSlide } from './DataGeneralSlide'
